# Generated by Django 2.2.19 on 2023-01-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_some_model_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Создайте уникальную ссылку', max_length=200),
        ),
    ]
