# Generated by Django 2.2.19 on 2023-01-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_review_changes_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Создайте уникальную ссылку', max_length=200, unique=True),
        ),
    ]
