# Generated by Django 2.2.19 on 2023-01-26 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_review_changes_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество ингредиентов должно быть не менее 1')], verbose_name='Amount'),
        ),
    ]
